/* Contents autogenerated by dyna_tools.py */
const char *lily_dynaload_table[] = {
    "\2Result\0Conn\0"
    ,"C\3Result"
    ,"m\0close\0(Result)"
    ,"m\0each_row\0(Result,Function(List[String]))"
    ,"m\0row_count\0(Result):Integer"
    ,"C\2Conn"
    ,"m\0query\0(Conn,String,String...):Either[String,Result]"
    ,"m\0open\0(*String,*String,*String,*String,*String):Either[String,Conn]"
    ,"Z"
};
