/* Contents autogenerated by dyna_tools.py */
#define ARG_Result(state, index) \
(lily_postgres_Result *) lily_arg_generic(s, index)

#define ID_Result(state) lily_cid_at(state, 0)

#define INIT_Result(state, target) \
target = lily_malloc(sizeof(lily_postgres_Result)); \
target->refcount = 0; \
target->destroy_func = (lily_destroy_func)destroy_Result;


#define ARG_Conn(state, index) \
(lily_postgres_Conn *) lily_arg_generic(s, index)

#define ID_Conn(state) lily_cid_at(state, 1)

#define INIT_Conn(state, target) \
target = lily_malloc(sizeof(lily_postgres_Conn)); \
target->refcount = 0; \
target->destroy_func = (lily_destroy_func)destroy_Conn;
